spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:3306}/wellness_activity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
spring.datasource.username=${LOCAL_MYSQL_USERNAME:wellness}
spring.datasource.password=${LOCAL_MYSQL_PASSWORD:wellness}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
